# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: framecurve 2.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "framecurve"
  s.version = "2.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Julik"]
  s.date = "2014-10-20"
  s.description = " Parser, validation and interpolation"
  s.email = "me@julik.nl"
  s.executables = ["framecurve_from_fcp_xml", "framecurve_validator"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "History.txt",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/framecurve_from_fcp_xml",
    "bin/framecurve_validator",
    "framecurve.gemspec",
    "lib/framecurve.rb",
    "lib/framecurve/comment.rb",
    "lib/framecurve/curve.rb",
    "lib/framecurve/extractors/fcp_xml.rb",
    "lib/framecurve/extractors/xml_bridge.rb",
    "lib/framecurve/parser.rb",
    "lib/framecurve/serializer.rb",
    "lib/framecurve/tuple.rb",
    "lib/framecurve/validator.rb",
    "test/fixtures/countdown_standard/countdown_asis 001.png",
    "test/fixtures/countdown_standard/countdown_asis 002.png",
    "test/fixtures/countdown_standard/countdown_asis 003.png",
    "test/fixtures/countdown_standard/countdown_asis 004.png",
    "test/fixtures/countdown_standard/countdown_asis 005.png",
    "test/fixtures/countdown_standard/countdown_asis 006.png",
    "test/fixtures/countdown_standard/countdown_asis 007.png",
    "test/fixtures/countdown_standard/countdown_asis 008.png",
    "test/fixtures/countdown_standard/countdown_asis 009.png",
    "test/fixtures/countdown_standard/countdown_asis 010.png",
    "test/fixtures/countdown_standard/countdown_asis 011.png",
    "test/fixtures/countdown_standard/countdown_asis 012.png",
    "test/fixtures/countdown_standard/countdown_asis 013.png",
    "test/fixtures/countdown_standard/countdown_asis 014.png",
    "test/fixtures/countdown_standard/countdown_asis 015.png",
    "test/fixtures/countdown_standard/countdown_asis 016.png",
    "test/fixtures/countdown_standard/countdown_asis 017.png",
    "test/fixtures/countdown_standard/countdown_asis 018.png",
    "test/fixtures/countdown_standard/countdown_asis 019.png",
    "test/fixtures/countdown_standard/countdown_asis 020.png",
    "test/fixtures/countdown_standard/countdown_asis 021.png",
    "test/fixtures/countdown_standard/countdown_asis 022.png",
    "test/fixtures/countdown_standard/countdown_asis 023.png",
    "test/fixtures/countdown_standard/countdown_asis 024.png",
    "test/fixtures/countdown_standard/countdown_asis 025.png",
    "test/fixtures/countdown_standard/countdown_asis 026.png",
    "test/fixtures/countdown_standard/countdown_asis 027.png",
    "test/fixtures/countdown_standard/countdown_asis 028.png",
    "test/fixtures/countdown_standard/countdown_asis 029.png",
    "test/fixtures/countdown_standard/countdown_asis 030.png",
    "test/fixtures/countdown_standard/countdown_asis 031.png",
    "test/fixtures/countdown_standard/countdown_asis 032.png",
    "test/fixtures/countdown_standard/countdown_asis 033.png",
    "test/fixtures/countdown_standard/countdown_asis 034.png",
    "test/fixtures/countdown_standard/countdown_asis 035.png",
    "test/fixtures/countdown_standard/countdown_asis 036.png",
    "test/fixtures/countdown_standard/countdown_asis 037.png",
    "test/fixtures/countdown_standard/countdown_asis 038.png",
    "test/fixtures/countdown_standard/countdown_asis 039.png",
    "test/fixtures/countdown_standard/countdown_asis 040.png",
    "test/fixtures/countdown_standard/countdown_asis 041.png",
    "test/fixtures/countdown_standard/countdown_asis 042.png",
    "test/fixtures/countdown_standard/countdown_asis 043.png",
    "test/fixtures/countdown_standard/countdown_asis 044.png",
    "test/fixtures/countdown_standard/countdown_asis 045.png",
    "test/fixtures/countdown_standard/countdown_asis 046.png",
    "test/fixtures/countdown_standard/countdown_asis 047.png",
    "test/fixtures/countdown_standard/countdown_asis 048.png",
    "test/fixtures/countdown_standard/countdown_asis 049.png",
    "test/fixtures/countdown_standard/countdown_asis 050.png",
    "test/fixtures/countdown_standard/countdown_asis 051.png",
    "test/fixtures/countdown_standard/countdown_asis 052.png",
    "test/fixtures/countdown_standard/countdown_asis 053.png",
    "test/fixtures/countdown_standard/countdown_asis 054.png",
    "test/fixtures/countdown_standard/countdown_asis 055.png",
    "test/fixtures/countdown_standard/countdown_asis 056.png",
    "test/fixtures/countdown_standard/countdown_asis 057.png",
    "test/fixtures/countdown_standard/countdown_asis 058.png",
    "test/fixtures/countdown_standard/countdown_asis 059.png",
    "test/fixtures/countdown_standard/countdown_asis 060.png",
    "test/fixtures/countdown_standard/countdown_asis 061.png",
    "test/fixtures/countdown_standard/countdown_asis 062.png",
    "test/fixtures/countdown_standard/countdown_asis 063.png",
    "test/fixtures/countdown_standard/countdown_asis 064.png",
    "test/fixtures/countdown_standard/countdown_asis 065.png",
    "test/fixtures/countdown_standard/countdown_asis 066.png",
    "test/fixtures/countdown_standard/countdown_asis 067.png",
    "test/fixtures/countdown_standard/countdown_asis 068.png",
    "test/fixtures/countdown_standard/countdown_asis 069.png",
    "test/fixtures/countdown_standard/countdown_asis 070.png",
    "test/fixtures/countdown_standard/countdown_asis 071.png",
    "test/fixtures/countdown_standard/countdown_asis 072.png",
    "test/fixtures/countdown_standard/countdown_asis 073.png",
    "test/fixtures/countdown_standard/countdown_asis 074.png",
    "test/fixtures/countdown_standard/countdown_asis 075.png",
    "test/fixtures/countdown_standard/countdown_asis 076.png",
    "test/fixtures/countdown_standard/countdown_asis 077.png",
    "test/fixtures/countdown_standard/countdown_asis 078.png",
    "test/fixtures/countdown_standard/countdown_asis 079.png",
    "test/fixtures/countdown_standard/countdown_asis 080.png",
    "test/fixtures/countdown_standard/countdown_asis 081.png",
    "test/fixtures/countdown_standard/countdown_asis 082.png",
    "test/fixtures/countdown_standard/countdown_asis 083.png",
    "test/fixtures/countdown_standard/countdown_asis 084.png",
    "test/fixtures/countdown_standard/countdown_asis 085.png",
    "test/fixtures/countdown_standard/countdown_asis 086.png",
    "test/fixtures/countdown_standard/countdown_asis 087.png",
    "test/fixtures/countdown_standard/countdown_asis 088.png",
    "test/fixtures/countdown_standard/countdown_asis 089.png",
    "test/fixtures/countdown_standard/countdown_asis 090.png",
    "test/fixtures/countdown_standard/countdown_asis 091.png",
    "test/fixtures/countdown_standard/countdown_asis 092.png",
    "test/fixtures/countdown_standard/countdown_asis 093.png",
    "test/fixtures/countdown_standard/countdown_asis 094.png",
    "test/fixtures/countdown_standard/countdown_asis 095.png",
    "test/fixtures/countdown_standard/countdown_asis 096.png",
    "test/fixtures/countdown_standard/countdown_asis 097.png",
    "test/fixtures/countdown_standard/countdown_asis 098.png",
    "test/fixtures/countdown_standard/countdown_asis 099.png",
    "test/fixtures/countdown_standard/countdown_asis 100.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 01.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 02.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 03.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 04.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 05.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 06.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 07.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 08.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 09.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 10.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 11.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 12.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 13.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 14.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 15.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 16.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 17.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 18.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 19.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 20.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 21.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 22.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 23.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 24.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 25.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 26.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 27.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 28.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 29.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 30.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 31.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 32.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 33.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 34.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 35.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 36.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 37.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 38.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 39.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 40.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 41.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 42.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 43.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 44.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 45.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 46.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 47.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 48.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 49.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed 50.png",
    "test/fixtures/countdown_timewarped/countdown_varispeed.framecurve.txt",
    "test/fixtures/fcp_xml/CountDOWN.xml",
    "test/fixtures/framecurves/err-neg-frames.framecurve.txt",
    "test/fixtures/framecurves/err-no-tuples.framecurve.txt",
    "test/fixtures/framecurves/incorrect.extension",
    "test/fixtures/framecurves/sample_framecurve1.framecurve.txt",
    "test/helper.rb",
    "test/test_framecurve_comment.rb",
    "test/test_framecurve_curve.rb",
    "test/test_framecurve_from_fcp_xml_binary.rb",
    "test/test_framecurve_parser.rb",
    "test/test_framecurve_serializer.rb",
    "test/test_framecurve_tuple.rb",
    "test/test_framecurve_validator.rb",
    "test/test_framecurve_validator_binary.rb"
  ]
  s.homepage = "http://github.com/guerilla-di/framecurve"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Handles Framecurve files"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<cli_test>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<cli_test>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<cli_test>, [">= 0"])
  end
end

